[2022-08-09 10:43:54.268] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f4f6a7d8640>
[2022-08-09 10:44:01.389] DEBUG: update.db @ 120: Closing db
[2022-08-09 10:44:01.390] DEBUG: update.db @ 122: Closed db
[2022-08-09 10:44:01.390] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 10:59:02.480] INFO: update.update @ 249: 2022
[2022-08-09 10:59:02.480] INFO: update.update @ 254: CAV
[2022-08-09 10:59:02.481] DEBUG: update.db @ 112: Loading db
[2022-08-09 10:59:02.482] INFO: update.update @ 258: 81
[2022-08-09 10:59:02.482] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 10:59:08.88] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f4f6a60abe0>
[2022-08-09 10:59:15.422] DEBUG: update.db @ 120: Closing db
[2022-08-09 10:59:15.422] DEBUG: update.db @ 122: Closed db
[2022-08-09 10:59:15.422] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 11:14:16.553] INFO: update.update @ 249: 2022
[2022-08-09 11:14:16.553] INFO: update.update @ 254: CAV
[2022-08-09 11:14:16.553] DEBUG: update.db @ 112: Loading db
[2022-08-09 11:14:16.555] INFO: update.update @ 258: 81
[2022-08-09 11:14:16.555] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 11:14:22.495] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f4f6a3d37f0>
[2022-08-09 11:14:29.121] DEBUG: update.db @ 120: Closing db
[2022-08-09 11:14:29.121] DEBUG: update.db @ 122: Closed db
[2022-08-09 11:14:29.122] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 11:29:30.151] INFO: update.update @ 249: 2022
[2022-08-09 11:29:30.152] INFO: update.update @ 254: CAV
[2022-08-09 11:29:30.152] DEBUG: update.db @ 112: Loading db
[2022-08-09 11:29:30.154] INFO: update.update @ 258: 81
[2022-08-09 11:29:30.155] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 11:29:37.594] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f4f6a2172e0>
[2022-08-09 11:29:43.957] DEBUG: update.db @ 120: Closing db
[2022-08-09 11:29:43.957] DEBUG: update.db @ 122: Closed db
[2022-08-09 11:29:43.958] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 11:44:44.999] INFO: update.update @ 249: 2022
[2022-08-09 11:44:44.999] INFO: update.update @ 254: CAV
[2022-08-09 11:44:44.999] DEBUG: update.db @ 112: Loading db
[2022-08-09 11:44:45.1] INFO: update.update @ 258: 81
[2022-08-09 11:44:45.2] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 11:44:51.657] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f4f6a0541f0>
[2022-08-09 11:44:58.339] DEBUG: update.db @ 120: Closing db
[2022-08-09 11:44:58.340] DEBUG: update.db @ 122: Closed db
[2022-08-09 11:44:58.340] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 11:59:59.366] INFO: update.update @ 249: 2022
[2022-08-09 11:59:59.366] INFO: update.update @ 254: CAV
[2022-08-09 11:59:59.366] DEBUG: update.db @ 112: Loading db
[2022-08-09 11:59:59.369] INFO: update.update @ 258: 81
[2022-08-09 11:59:59.371] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 12:00:05.776] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f4f69e90b80>
[2022-08-09 12:00:12.458] DEBUG: update.db @ 120: Closing db
[2022-08-09 12:00:12.458] DEBUG: update.db @ 122: Closed db
[2022-08-09 12:00:12.459] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 12:15:13.483] INFO: update.update @ 249: 2022
[2022-08-09 12:15:13.483] INFO: update.update @ 254: CAV
[2022-08-09 12:15:13.484] DEBUG: update.db @ 112: Loading db
[2022-08-09 12:15:13.485] INFO: update.update @ 258: 81
[2022-08-09 12:15:13.486] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 12:15:19.967] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f4f69cd0430>
[2022-08-09 12:15:25.912] DEBUG: update.db @ 120: Closing db
[2022-08-09 12:15:25.912] DEBUG: update.db @ 122: Closed db
[2022-08-09 12:15:25.913] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 12:45:46.326] INFO: __init__.create_app @ 30: App startup in production mode
[2022-08-09 12:45:46.330] INFO: update.update_public_holidays @ 215: Updating public holidays
[2022-08-09 12:45:46.331] DEBUG: update.db @ 112: Loading db
[2022-08-09 12:45:47.954] DEBUG: update.update_public_holidays @ 228: Updated public holidays
[2022-08-09 12:45:47.954] DEBUG: update.public_holidays @ 196: Loading public holidays
[2022-08-09 12:45:47.959] INFO: update.update @ 249: 2022
[2022-08-09 12:45:47.959] INFO: update.update @ 254: CAV
[2022-08-09 12:45:47.962] INFO: update.update @ 258: 81
[2022-08-09 12:45:47.962] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 12:45:55.760] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b7dd2b0>
[2022-08-09 12:46:02.757] DEBUG: update.db @ 120: Closing db
[2022-08-09 12:46:02.758] DEBUG: update.db @ 122: Closed db
[2022-08-09 12:46:02.759] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 13:01:03.931] INFO: update.update @ 249: 2022
[2022-08-09 13:01:03.931] INFO: update.update @ 254: CAV
[2022-08-09 13:01:03.932] DEBUG: update.db @ 112: Loading db
[2022-08-09 13:01:03.934] INFO: update.update @ 258: 81
[2022-08-09 13:01:03.938] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 13:01:11.412] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b60b730>
[2022-08-09 13:01:18.460] DEBUG: update.db @ 120: Closing db
[2022-08-09 13:01:18.460] DEBUG: update.db @ 122: Closed db
[2022-08-09 13:01:18.461] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 13:16:19.716] INFO: update.update @ 249: 2022
[2022-08-09 13:16:19.717] INFO: update.update @ 254: CAV
[2022-08-09 13:16:19.717] DEBUG: update.db @ 112: Loading db
[2022-08-09 13:16:19.721] INFO: update.update @ 258: 81
[2022-08-09 13:16:19.721] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 13:16:26.544] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b3d6220>
[2022-08-09 13:16:33.252] DEBUG: update.db @ 120: Closing db
[2022-08-09 13:16:33.252] DEBUG: update.db @ 122: Closed db
[2022-08-09 13:16:33.253] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 13:31:34.376] INFO: update.update @ 249: 2022
[2022-08-09 13:31:34.376] INFO: update.update @ 254: CAV
[2022-08-09 13:31:34.377] DEBUG: update.db @ 112: Loading db
[2022-08-09 13:31:34.378] INFO: update.update @ 258: 81
[2022-08-09 13:31:34.378] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 13:31:40.747] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b3c0850>
[2022-08-09 13:31:47.295] DEBUG: update.db @ 120: Closing db
[2022-08-09 13:31:47.296] DEBUG: update.db @ 122: Closed db
[2022-08-09 13:31:47.298] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 13:46:48.602] INFO: update.update @ 249: 2022
[2022-08-09 13:46:48.602] INFO: update.update @ 254: CAV
[2022-08-09 13:46:48.602] DEBUG: update.db @ 112: Loading db
[2022-08-09 13:46:48.606] INFO: update.update @ 258: 81
[2022-08-09 13:46:48.606] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 13:46:54.835] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b0c8a00>
[2022-08-09 13:47:00.998] DEBUG: update.db @ 120: Closing db
[2022-08-09 13:47:00.999] DEBUG: update.db @ 122: Closed db
[2022-08-09 13:47:01.0] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 14:02:02.260] INFO: update.update @ 249: 2022
[2022-08-09 14:02:02.260] INFO: update.update @ 254: CAV
[2022-08-09 14:02:02.261] DEBUG: update.db @ 112: Loading db
[2022-08-09 14:02:02.263] INFO: update.update @ 258: 81
[2022-08-09 14:02:02.263] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 14:02:08.136] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8ae17490>
[2022-08-09 14:02:14.836] DEBUG: update.db @ 120: Closing db
[2022-08-09 14:02:14.837] DEBUG: update.db @ 122: Closed db
[2022-08-09 14:02:14.837] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 14:17:15.978] INFO: update.update @ 249: 2022
[2022-08-09 14:17:15.979] INFO: update.update @ 254: CAV
[2022-08-09 14:17:15.979] DEBUG: update.db @ 112: Loading db
[2022-08-09 14:17:15.980] INFO: update.update @ 258: 81
[2022-08-09 14:17:15.981] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 14:17:22.458] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8ac51d00>
[2022-08-09 14:17:28.884] DEBUG: update.db @ 120: Closing db
[2022-08-09 14:17:28.884] DEBUG: update.db @ 122: Closed db
[2022-08-09 14:17:28.885] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 14:32:30.56] INFO: update.update @ 249: 2022
[2022-08-09 14:32:30.56] INFO: update.update @ 254: CAV
[2022-08-09 14:32:30.57] DEBUG: update.db @ 112: Loading db
[2022-08-09 14:32:30.58] INFO: update.update @ 258: 81
[2022-08-09 14:32:30.58] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 14:32:38.111] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5ca10ab970>
[2022-08-09 14:32:44.789] DEBUG: update.db @ 120: Closing db
[2022-08-09 14:32:44.790] DEBUG: update.db @ 122: Closed db
[2022-08-09 14:32:44.790] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 14:47:45.981] INFO: update.update @ 249: 2022
[2022-08-09 14:47:45.981] INFO: update.update @ 254: CAV
[2022-08-09 14:47:45.982] DEBUG: update.db @ 112: Loading db
[2022-08-09 14:47:45.985] INFO: update.update @ 258: 81
[2022-08-09 14:47:45.992] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 14:47:53.957] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b8c2be0>
[2022-08-09 14:48:00.576] DEBUG: update.db @ 120: Closing db
[2022-08-09 14:48:00.576] DEBUG: update.db @ 122: Closed db
[2022-08-09 14:48:00.576] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 15:03:01.845] INFO: update.update @ 249: 2022
[2022-08-09 15:03:01.845] INFO: update.update @ 254: CAV
[2022-08-09 15:03:01.846] DEBUG: update.db @ 112: Loading db
[2022-08-09 15:03:01.847] INFO: update.update @ 258: 81
[2022-08-09 15:03:01.847] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 15:03:08.577] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8af90430>
[2022-08-09 15:03:15.169] DEBUG: update.db @ 120: Closing db
[2022-08-09 15:03:15.169] DEBUG: update.db @ 122: Closed db
[2022-08-09 15:03:15.170] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 15:18:16.377] INFO: update.update @ 249: 2022
[2022-08-09 15:18:16.377] INFO: update.update @ 254: CAV
[2022-08-09 15:18:16.377] DEBUG: update.db @ 112: Loading db
[2022-08-09 15:18:16.381] INFO: update.update @ 258: 81
[2022-08-09 15:18:16.381] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 15:18:24.537] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b2aa220>
[2022-08-09 15:18:30.730] DEBUG: update.db @ 120: Closing db
[2022-08-09 15:18:30.730] DEBUG: update.db @ 122: Closed db
[2022-08-09 15:18:30.735] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 15:33:32.20] INFO: update.update @ 249: 2022
[2022-08-09 15:33:32.20] INFO: update.update @ 254: CAV
[2022-08-09 15:33:32.20] DEBUG: update.db @ 112: Loading db
[2022-08-09 15:33:32.22] INFO: update.update @ 258: 81
[2022-08-09 15:33:32.22] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 15:33:40.366] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b71bbb0>
[2022-08-09 15:33:46.867] DEBUG: update.db @ 120: Closing db
[2022-08-09 15:33:46.867] DEBUG: update.db @ 122: Closed db
[2022-08-09 15:33:46.872] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 15:48:48.241] INFO: update.update @ 249: 2022
[2022-08-09 15:48:48.242] INFO: update.update @ 254: CAV
[2022-08-09 15:48:48.242] DEBUG: update.db @ 112: Loading db
[2022-08-09 15:48:48.246] INFO: update.update @ 258: 81
[2022-08-09 15:48:48.247] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 15:49:00.388] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b328430>
[2022-08-09 15:49:06.592] DEBUG: update.db @ 120: Closing db
[2022-08-09 15:49:06.592] DEBUG: update.db @ 122: Closed db
[2022-08-09 15:49:06.594] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 16:04:08.85] INFO: update.update @ 249: 2022
[2022-08-09 16:04:08.87] INFO: update.update @ 254: CAV
[2022-08-09 16:04:08.87] DEBUG: update.db @ 112: Loading db
[2022-08-09 16:04:08.91] INFO: update.update @ 258: 81
[2022-08-09 16:04:08.91] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 16:04:15.192] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8af5b220>
[2022-08-09 16:04:22.224] DEBUG: update.db @ 120: Closing db
[2022-08-09 16:04:22.224] DEBUG: update.db @ 122: Closed db
[2022-08-09 16:04:22.225] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 16:19:23.891] INFO: update.update @ 249: 2022
[2022-08-09 16:19:23.892] INFO: update.update @ 254: CAV
[2022-08-09 16:19:23.892] DEBUG: update.db @ 112: Loading db
[2022-08-09 16:19:23.895] INFO: update.update @ 258: 81
[2022-08-09 16:19:23.895] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 16:19:30.787] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8aa94be0>
[2022-08-09 16:19:37.287] DEBUG: update.db @ 120: Closing db
[2022-08-09 16:19:37.287] DEBUG: update.db @ 122: Closed db
[2022-08-09 16:19:37.288] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 16:34:39.14] INFO: update.update @ 249: 2022
[2022-08-09 16:34:39.14] INFO: update.update @ 254: CAV
[2022-08-09 16:34:39.14] DEBUG: update.db @ 112: Loading db
[2022-08-09 16:34:39.23] INFO: update.update @ 258: 81
[2022-08-09 16:34:39.24] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 16:34:50.340] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5ca003e760>
[2022-08-09 16:34:56.969] DEBUG: update.db @ 120: Closing db
[2022-08-09 16:34:56.970] DEBUG: update.db @ 122: Closed db
[2022-08-09 16:34:56.971] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 16:49:58.609] INFO: update.update @ 249: 2022
[2022-08-09 16:49:58.610] INFO: update.update @ 254: CAV
[2022-08-09 16:49:58.610] DEBUG: update.db @ 112: Loading db
[2022-08-09 16:49:58.619] INFO: update.update @ 258: 81
[2022-08-09 16:49:58.626] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 16:50:05.18] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b8a9f70>
[2022-08-09 16:50:12.37] DEBUG: update.db @ 120: Closing db
[2022-08-09 16:50:12.37] DEBUG: update.db @ 122: Closed db
[2022-08-09 16:50:12.38] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 17:05:13.825] INFO: update.update @ 249: 2022
[2022-08-09 17:05:13.826] INFO: update.update @ 254: CAV
[2022-08-09 17:05:13.827] DEBUG: update.db @ 112: Loading db
[2022-08-09 17:05:13.829] INFO: update.update @ 258: 81
[2022-08-09 17:05:13.830] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 17:05:20.773] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b710970>
[2022-08-09 17:05:27.991] DEBUG: update.db @ 120: Closing db
[2022-08-09 17:05:27.991] DEBUG: update.db @ 122: Closed db
[2022-08-09 17:05:27.992] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 17:20:29.888] INFO: update.update @ 249: 2022
[2022-08-09 17:20:29.888] INFO: update.update @ 254: CAV
[2022-08-09 17:20:29.888] DEBUG: update.db @ 112: Loading db
[2022-08-09 17:20:29.897] INFO: update.update @ 258: 81
[2022-08-09 17:20:29.897] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 17:20:37.89] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b1a61f0>
[2022-08-09 17:20:43.943] DEBUG: update.db @ 120: Closing db
[2022-08-09 17:20:43.944] DEBUG: update.db @ 122: Closed db
[2022-08-09 17:20:43.944] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 17:35:45.380] INFO: update.update @ 249: 2022
[2022-08-09 17:35:45.381] INFO: update.update @ 254: CAV
[2022-08-09 17:35:45.381] DEBUG: update.db @ 112: Loading db
[2022-08-09 17:35:45.382] INFO: update.update @ 258: 81
[2022-08-09 17:35:45.383] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 17:35:51.648] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b0e3fd0>
[2022-08-09 17:35:59.10] DEBUG: update.db @ 120: Closing db
[2022-08-09 17:35:59.12] DEBUG: update.db @ 122: Closed db
[2022-08-09 17:35:59.14] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 17:51:00.713] INFO: update.update @ 249: 2022
[2022-08-09 17:51:00.714] INFO: update.update @ 254: CAV
[2022-08-09 17:51:00.714] DEBUG: update.db @ 112: Loading db
[2022-08-09 17:51:00.718] INFO: update.update @ 258: 81
[2022-08-09 17:51:00.719] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-09 17:51:08.193] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5c8b2848e0>
[2022-08-09 17:51:14.551] DEBUG: update.db @ 120: Closing db
[2022-08-09 17:51:14.551] DEBUG: update.db @ 122: Closed db
[2022-08-09 17:51:14.552] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-09 18:06:16.344] DEBUG: update.db @ 120: Closing db
[2022-08-09 18:06:16.346] DEBUG: update.db @ 122: Closed db
[2022-08-09 18:06:16.346] INFO: update.update_db @ 87: Sleeping for 50023 seconds
[2022-08-09 21:16:50.445] INFO: __init__.create_app @ 30: App startup in production mode
[2022-08-09 21:16:50.447] INFO: update.update_public_holidays @ 215: Updating public holidays
[2022-08-09 21:16:50.448] DEBUG: update.db @ 112: Loading db
[2022-08-09 21:16:51.926] DEBUG: update.update_public_holidays @ 228: Updated public holidays
[2022-08-09 21:16:51.926] DEBUG: update.public_holidays @ 196: Loading public holidays
[2022-08-09 21:16:51.929] DEBUG: update.db @ 120: Closing db
[2022-08-09 21:16:51.930] DEBUG: update.db @ 122: Closed db
[2022-08-09 21:16:51.930] INFO: update.update_db @ 87: Sleeping for 38589 seconds
[2022-08-10 06:24:24.665] INFO: __init__.create_app @ 30: App startup in production mode
[2022-08-10 06:24:24.666] INFO: update.update_public_holidays @ 215: Updating public holidays
[2022-08-10 06:24:24.667] DEBUG: update.db @ 112: Loading db
[2022-08-10 06:24:26.254] DEBUG: update.update_public_holidays @ 228: Updated public holidays
[2022-08-10 06:24:26.254] DEBUG: update.public_holidays @ 196: Loading public holidays
[2022-08-10 06:24:26.257] DEBUG: update.db @ 120: Closing db
[2022-08-10 06:24:26.257] DEBUG: update.db @ 122: Closed db
[2022-08-10 06:24:26.258] INFO: update.update_db @ 87: Sleeping for 5735 seconds
[2022-08-10 08:00:06.379] INFO: update.update @ 249: 2022
[2022-08-10 08:00:06.380] INFO: update.update @ 254: CAV
[2022-08-10 08:00:06.380] DEBUG: update.db @ 112: Loading db
[2022-08-10 08:00:06.384] INFO: update.update @ 258: 81
[2022-08-10 08:00:06.384] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 08:00:13.693] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe4365d430>
[2022-08-10 08:00:21.398] DEBUG: update.db @ 120: Closing db
[2022-08-10 08:00:21.398] DEBUG: update.db @ 122: Closed db
[2022-08-10 08:00:21.398] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 08:15:22.220] INFO: update.update @ 249: 2022
[2022-08-10 08:15:22.221] INFO: update.update @ 254: CAV
[2022-08-10 08:15:22.221] DEBUG: update.db @ 112: Loading db
[2022-08-10 08:15:22.223] INFO: update.update @ 258: 81
[2022-08-10 08:15:22.224] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 08:15:27.818] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe434badc0>
[2022-08-10 08:15:33.969] DEBUG: update.db @ 120: Closing db
[2022-08-10 08:15:33.969] DEBUG: update.db @ 122: Closed db
[2022-08-10 08:15:33.969] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 08:30:34.791] INFO: update.update @ 249: 2022
[2022-08-10 08:30:34.792] INFO: update.update @ 254: CAV
[2022-08-10 08:30:34.792] DEBUG: update.db @ 112: Loading db
[2022-08-10 08:30:34.794] INFO: update.update @ 258: 81
[2022-08-10 08:30:34.795] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 08:30:40.728] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe4320c850>
[2022-08-10 08:30:47.852] DEBUG: update.db @ 120: Closing db
[2022-08-10 08:30:47.852] DEBUG: update.db @ 122: Closed db
[2022-08-10 08:30:47.853] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 08:45:48.721] INFO: update.update @ 249: 2022
[2022-08-10 08:45:48.722] INFO: update.update @ 254: CAV
[2022-08-10 08:45:48.722] DEBUG: update.db @ 112: Loading db
[2022-08-10 08:45:48.724] INFO: update.update @ 258: 81
[2022-08-10 08:45:48.725] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 08:45:54.332] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe43083610>
[2022-08-10 08:46:00.775] DEBUG: update.db @ 120: Closing db
[2022-08-10 08:46:00.775] DEBUG: update.db @ 122: Closed db
[2022-08-10 08:46:00.776] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 09:01:01.546] INFO: update.update @ 249: 2022
[2022-08-10 09:01:01.546] INFO: update.update @ 254: CAV
[2022-08-10 09:01:01.546] DEBUG: update.db @ 112: Loading db
[2022-08-10 09:01:01.548] INFO: update.update @ 258: 81
[2022-08-10 09:01:01.548] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 09:01:07.286] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe42e81df0>
[2022-08-10 09:01:14.140] DEBUG: update.db @ 120: Closing db
[2022-08-10 09:01:14.140] DEBUG: update.db @ 122: Closed db
[2022-08-10 09:01:14.141] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 09:16:15.64] INFO: update.update @ 249: 2022
[2022-08-10 09:16:15.64] INFO: update.update @ 254: CAV
[2022-08-10 09:16:15.65] DEBUG: update.db @ 112: Loading db
[2022-08-10 09:16:15.66] INFO: update.update @ 258: 81
[2022-08-10 09:16:15.67] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 09:16:22.49] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe42cc77c0>
[2022-08-10 09:16:28.761] DEBUG: update.db @ 120: Closing db
[2022-08-10 09:16:28.762] DEBUG: update.db @ 122: Closed db
[2022-08-10 09:16:28.762] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 09:31:29.660] INFO: update.update @ 249: 2022
[2022-08-10 09:31:29.664] INFO: update.update @ 254: CAV
[2022-08-10 09:31:29.665] DEBUG: update.db @ 112: Loading db
[2022-08-10 09:31:29.666] INFO: update.update @ 258: 81
[2022-08-10 09:31:29.668] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 09:31:36.83] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe42b0a070>
[2022-08-10 09:31:42.712] DEBUG: update.db @ 120: Closing db
[2022-08-10 09:31:42.712] DEBUG: update.db @ 122: Closed db
[2022-08-10 09:31:42.713] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 09:46:43.564] INFO: update.update @ 249: 2022
[2022-08-10 09:46:43.564] INFO: update.update @ 254: CAV
[2022-08-10 09:46:43.564] DEBUG: update.db @ 112: Loading db
[2022-08-10 09:46:43.566] INFO: update.update @ 258: 81
[2022-08-10 09:46:43.566] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 09:46:50.298] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe500a5ca0>
[2022-08-10 09:46:56.813] DEBUG: update.db @ 120: Closing db
[2022-08-10 09:46:56.814] DEBUG: update.db @ 122: Closed db
[2022-08-10 09:46:56.815] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 10:01:57.611] INFO: update.update @ 249: 2022
[2022-08-10 10:01:57.611] INFO: update.update @ 254: CAV
[2022-08-10 10:01:57.611] DEBUG: update.db @ 112: Loading db
[2022-08-10 10:01:57.612] INFO: update.update @ 258: 81
[2022-08-10 10:01:57.613] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 10:02:03.611] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe42d7afa0>
[2022-08-10 10:02:10.42] DEBUG: update.db @ 120: Closing db
[2022-08-10 10:02:10.43] DEBUG: update.db @ 122: Closed db
[2022-08-10 10:02:10.44] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 10:17:10.936] INFO: update.update @ 249: 2022
[2022-08-10 10:17:10.936] INFO: update.update @ 254: CAV
[2022-08-10 10:17:10.937] DEBUG: update.db @ 112: Loading db
[2022-08-10 10:17:10.938] INFO: update.update @ 258: 81
[2022-08-10 10:17:10.938] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 10:17:17.167] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe4375b7f0>
[2022-08-10 10:17:23.828] DEBUG: update.db @ 120: Closing db
[2022-08-10 10:17:23.828] DEBUG: update.db @ 122: Closed db
[2022-08-10 10:17:23.829] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 10:32:24.651] INFO: update.update @ 249: 2022
[2022-08-10 10:32:24.651] INFO: update.update @ 254: CAV
[2022-08-10 10:32:24.651] DEBUG: update.db @ 112: Loading db
[2022-08-10 10:32:24.653] INFO: update.update @ 258: 81
[2022-08-10 10:32:24.653] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 10:32:30.476] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe430675e0>
[2022-08-10 10:32:36.919] DEBUG: update.db @ 120: Closing db
[2022-08-10 10:32:36.919] DEBUG: update.db @ 122: Closed db
[2022-08-10 10:32:36.920] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 10:47:37.802] INFO: update.update @ 249: 2022
[2022-08-10 10:47:37.803] INFO: update.update @ 254: CAV
[2022-08-10 10:47:37.803] DEBUG: update.db @ 112: Loading db
[2022-08-10 10:47:37.806] INFO: update.update @ 258: 81
[2022-08-10 10:47:37.807] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 10:47:44.340] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe42fe6f70>
[2022-08-10 10:47:50.966] DEBUG: update.db @ 120: Closing db
[2022-08-10 10:47:50.966] DEBUG: update.db @ 122: Closed db
[2022-08-10 10:47:50.967] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 11:02:51.779] INFO: update.update @ 249: 2022
[2022-08-10 11:02:51.780] INFO: update.update @ 254: CAV
[2022-08-10 11:02:51.780] DEBUG: update.db @ 112: Loading db
[2022-08-10 11:02:51.781] INFO: update.update @ 258: 81
[2022-08-10 11:02:51.781] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 11:02:58.154] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.search_matter(Matter(matter_type, number, year, None, None, None))
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe430397f0>
[2022-08-10 11:03:04.810] DEBUG: update.db @ 120: Closing db
[2022-08-10 11:03:04.810] DEBUG: update.db @ 122: Closed db
[2022-08-10 11:03:04.811] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 11:18:05.898] INFO: update.update @ 249: 2022
[2022-08-10 11:18:05.898] INFO: update.update @ 254: CAV
[2022-08-10 11:18:05.899] DEBUG: update.db @ 112: Loading db
[2022-08-10 11:18:05.900] INFO: update.update @ 258: 81
[2022-08-10 11:18:05.901] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 11:18:12.160] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    #updater.add_scattered_pros()
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    while consecutive_missing < 50:
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    def search_matter(self, matter):
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    browser.submit_form(search_form)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe42e125e0>
[2022-08-10 11:18:18.384] DEBUG: update.db @ 120: Closing db
[2022-08-10 11:18:18.388] DEBUG: update.db @ 122: Closed db
[2022-08-10 11:18:18.389] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 11:33:19.482] INFO: update.update @ 249: 2022
[2022-08-10 11:33:19.486] INFO: update.update @ 254: CAV
[2022-08-10 11:33:19.487] DEBUG: update.db @ 112: Loading db
[2022-08-10 11:33:19.496] INFO: update.update @ 258: 81
[2022-08-10 11:33:19.496] DEBUG: update.browser @ 129: Starting RoboBrowser session
[2022-08-10 11:33:25.468] ERROR: update.update_db @ 78: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 71, in update_db
    pause = 0
  File "/home/runner/probate/probatewebapp/update.py", line 262, in update
    self.db.execute("DELETE FROM public_holidays WHERE year < ?",
  File "/home/runner/probate/probatewebapp/update.py", line 286, in search_matter
    for matter_type in MATTER_TYPES:
  File "/home/runner/probate/probatewebapp/update.py", line 143, in browser
    browser.open(LOGIN_URL)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7efe42949ee0>
[2022-08-10 11:33:31.968] DEBUG: update.db @ 120: Closing db
[2022-08-10 11:33:31.968] DEBUG: update.db @ 122: Closed db
[2022-08-10 11:33:31.970] INFO: update.update_db @ 87: Sleeping for 900 seconds
[2022-08-10 11:38:10.179] INFO: __init__.create_app @ 30: App startup in production mode
[2022-08-10 11:38:10.180] INFO: update.update_public_holidays @ 250: Updating public holidays
[2022-08-10 11:38:10.181] DEBUG: update.db @ 124: Loading db
[2022-08-10 11:38:12.54] DEBUG: update.update_public_holidays @ 265: Updated public holidays
[2022-08-10 11:38:12.55] DEBUG: update.public_holidays @ 227: Loading public holidays
[2022-08-10 11:38:12.58] INFO: update.update @ 286: 2022
[2022-08-10 11:38:12.59] INFO: update.update @ 291: CAV
[2022-08-10 11:38:12.60] INFO: update.update @ 295: 81
[2022-08-10 11:38:12.60] DEBUG: update.browser @ 141: Starting RoboBrowser session
[2022-08-10 11:38:18.598] ERROR: update.update_db @ 85: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 75, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 299, in update
    self.search_matter(
  File "/home/runner/probate/probatewebapp/update.py", line 329, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 155, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f1768c88e20>
[2022-08-10 11:38:23.969] DEBUG: update.db @ 132: Closing db
[2022-08-10 11:38:23.970] DEBUG: update.db @ 134: Closed db
[2022-08-10 11:38:23.970] INFO: update.update_db @ 99: Sleeping for 900 seconds
[2022-08-10 11:40:47.154] INFO: __init__.create_app @ 30: App startup in production mode
[2022-08-10 11:40:47.158] INFO: update.update_public_holidays @ 250: Updating public holidays
[2022-08-10 11:40:47.158] DEBUG: update.db @ 124: Loading db
[2022-08-10 11:40:48.505] DEBUG: update.update_public_holidays @ 265: Updated public holidays
[2022-08-10 11:40:48.505] DEBUG: update.public_holidays @ 227: Loading public holidays
[2022-08-10 11:40:48.509] INFO: update.update @ 286: 2022
[2022-08-10 11:40:48.510] INFO: update.update @ 291: CAV
[2022-08-10 11:40:48.511] INFO: update.update @ 295: 81
[2022-08-10 11:40:48.511] DEBUG: update.browser @ 141: Starting RoboBrowser session
[2022-08-10 11:40:54.587] ERROR: update.update_db @ 85: Unexpected error: current_matter=Matter(type='CAV', number=82, year=2022, title=None, deceased_name=None, flags=None): 
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 75, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 299, in update
    self.search_matter(
  File "/home/runner/probate/probatewebapp/update.py", line 329, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 155, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7fae9b025f40>
[2022-08-10 11:41:01.432] DEBUG: update.db @ 132: Closing db
[2022-08-10 11:41:01.432] DEBUG: update.db @ 134: Closed db
[2022-08-10 11:41:01.433] INFO: update.update_db @ 99: Sleeping for 900 seconds
[2022-08-10 11:44:03.465] INFO: __init__.create_app @ 30: App startup in production mode
[2022-08-10 11:44:03.466] INFO: update.update_public_holidays @ 250: Updating public holidays
[2022-08-10 11:44:03.468] DEBUG: update.db @ 124: Loading db
[2022-08-10 11:44:09.742] DEBUG: update.update_public_holidays @ 265: Updated public holidays
[2022-08-10 11:44:09.742] DEBUG: update.public_holidays @ 227: Loading public holidays
[2022-08-10 11:44:09.747] INFO: update.update @ 286: 2022
[2022-08-10 11:44:09.748] INFO: update.update @ 291: CAV
[2022-08-10 11:44:09.748] INFO: update.update @ 295: 81
[2022-08-10 11:44:09.748] DEBUG: update.browser @ 141: Starting RoboBrowser session
[2022-08-10 11:44:15.523] ERROR: update.update_db @ 81: Elodgment change exception:
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 156, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f48de9b8f40>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 75, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 299, in update
    self.search_matter(
  File "/home/runner/probate/probatewebapp/update.py", line 329, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 159, in browser
    raise ElodgmentChangeException(
probatewebapp.update.ElodgmentChangeException: No "Probate" option in eLodgment: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f48de9b8f40>
[2022-08-10 11:44:22.72] DEBUG: update.db @ 132: Closing db
[2022-08-10 11:44:22.72] DEBUG: update.db @ 134: Closed db
[2022-08-10 11:44:22.73] INFO: update.update_db @ 99: Sleeping for 86400 seconds
[2022-08-11 05:39:32.97] INFO: __init__.create_app @ 30: App startup in production mode
[2022-08-11 05:39:32.98] INFO: update.update_public_holidays @ 250: Updating public holidays
[2022-08-11 05:39:32.99] DEBUG: update.db @ 124: Loading db
[2022-08-11 05:39:33.739] DEBUG: update.update_public_holidays @ 265: Updated public holidays
[2022-08-11 05:39:33.739] DEBUG: update.public_holidays @ 227: Loading public holidays
[2022-08-11 05:39:33.742] DEBUG: update.db @ 132: Closing db
[2022-08-11 05:39:33.743] DEBUG: update.db @ 134: Closed db
[2022-08-11 05:39:33.743] INFO: update.update_db @ 99: Sleeping for 8427 seconds
[2022-08-11 08:00:09.405] INFO: update.update @ 286: 2022
[2022-08-11 08:00:09.406] INFO: update.update @ 291: CAV
[2022-08-11 08:00:09.406] DEBUG: update.db @ 124: Loading db
[2022-08-11 08:00:09.410] INFO: update.update @ 295: 81
[2022-08-11 08:00:09.410] DEBUG: update.browser @ 141: Starting RoboBrowser session
[2022-08-11 08:00:16.857] ERROR: update.update_db @ 81: Elodgment change exception:
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 156, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f29a07e5f10>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 75, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 299, in update
    self.search_matter(
  File "/home/runner/probate/probatewebapp/update.py", line 329, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 159, in browser
    raise ElodgmentChangeException(
probatewebapp.update.ElodgmentChangeException: No "Probate" option in eLodgment: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f29a07e5f10>
[2022-08-11 08:00:23.111] DEBUG: update.db @ 132: Closing db
[2022-08-11 08:00:23.111] DEBUG: update.db @ 134: Closed db
[2022-08-11 08:00:23.112] INFO: update.update_db @ 99: Sleeping for 86400 seconds
[2022-08-11 10:14:34.276] INFO: __init__.create_app @ 30: App startup in production mode
[2022-08-11 10:14:34.277] INFO: update.update_public_holidays @ 250: Updating public holidays
[2022-08-11 10:14:34.278] DEBUG: update.db @ 124: Loading db
[2022-08-11 10:14:35.236] DEBUG: update.update_public_holidays @ 265: Updated public holidays
[2022-08-11 10:14:35.236] DEBUG: update.public_holidays @ 227: Loading public holidays
[2022-08-11 10:14:35.240] INFO: update.update @ 286: 2022
[2022-08-11 10:14:35.240] INFO: update.update @ 291: CAV
[2022-08-11 10:14:35.242] INFO: update.update @ 295: 81
[2022-08-11 10:14:35.242] DEBUG: update.browser @ 141: Starting RoboBrowser session
[2022-08-11 10:14:40.551] ERROR: update.update_db @ 81: Elodgment change exception:
Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 156, in browser
    search_form[DIVISION_SELECTOR_NAME].value = 'Probate'
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 109, in value
    self._value = self._value_to_index(value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/robobrowser/forms/fields.py", line 99, in _value_to_index
    raise ValueError('Option {0} not found in field {1!r}'.format(value, self))
ValueError: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5a0cf526a0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/probate/probatewebapp/update.py", line 75, in update_db
    updater.update(years)
  File "/home/runner/probate/probatewebapp/update.py", line 299, in update
    self.search_matter(
  File "/home/runner/probate/probatewebapp/update.py", line 329, in search_matter
    search_form = self.browser.get_form()
  File "/home/runner/probate/probatewebapp/update.py", line 159, in browser
    raise ElodgmentChangeException(
probatewebapp.update.ElodgmentChangeException: No "Probate" option in eLodgment: Option Probate not found in field <robobrowser.forms.fields.Select object at 0x7f5a0cf526a0>
[2022-08-11 10:14:47.157] DEBUG: update.db @ 132: Closing db
[2022-08-11 10:14:47.157] DEBUG: update.db @ 134: Closed db
[2022-08-11 10:14:47.158] INFO: update.update_db @ 99: Sleeping for 86400 seconds
[2022-08-11 12:32:13.388] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-11 12:35:39.374] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-11 21:31:20.692] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-11 23:02:55.148] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-12 04:20:06.349] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-12 14:26:01.845] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-12 14:53:57.689] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-13 00:55:32.585] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-13 04:11:00.674] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-13 15:28:44.967] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-14 11:43:50.83] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-14 11:58:49.866] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-15 00:46:59.63] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-15 09:48:37.48] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-15 11:34:10.249] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-16 06:19:58.264] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-16 21:05:14.828] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-17 06:21:08.5] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-17 19:07:03.234] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-18 05:55:49.360] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-18 07:26:33.777] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-18 14:44:40.651] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-19 04:51:33.415] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-19 11:36:26.940] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-19 22:21:10.24] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-20 19:07:22.974] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-21 14:07:46.368] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-22 04:50:18.500] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-22 16:37:13.916] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-23 07:27:53.597] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-23 11:00:40.292] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-23 11:01:22.760] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-23 21:52:49.829] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-24 04:53:52.255] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-24 08:53:21.679] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-24 18:09:31.694] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-24 19:26:38.996] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-24 21:10:58.622] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-25 09:27:50.197] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-25 14:59:59.520] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-25 18:45:35.555] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-26 05:29:33.688] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-26 06:45:51.654] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-26 11:06:44.377] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-27 03:20:38.705] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-27 05:35:53.372] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 03:52:41.231] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 05:22:28.999] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 06:37:46.801] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 09:26:26.769] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 10:29:09.768] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 11:14:38.355] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 12:29:48.3] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 13:59:15.175] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 15:44:34.116] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 17:29:04.924] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 19:30:03.154] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 20:44:18.421] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 21:59:59.163] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 22:31:42.406] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-28 23:35:03.983] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-29 11:41:32.810] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-29 12:42:25.437] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-29 14:29:43.10] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-29 15:31:24.135] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-30 03:08:48.483] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-30 04:45:11.117] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-30 05:47:29.651] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-30 08:48:42.889] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-30 10:33:55.831] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-30 11:48:23.526] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-31 08:06:41.910] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-31 10:19:37.681] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-31 13:55:21.971] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-31 14:55:20.981] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-31 16:25:28.365] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-31 18:40:26.819] INFO: __init__.create_app @ 31: App startup in production mode
[2022-08-31 22:40:26.410] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-01 01:55:26.135] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-01 04:55:30.353] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-01 13:01:24.973] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-01 14:46:26.859] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-01 16:01:16.156] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-01 16:46:25.569] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-01 18:01:21.609] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-01 20:16:27.796] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-02 00:46:27.928] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-02 07:54:37.341] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-02 12:24:45.762] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-02 14:11:36.209] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-02 15:56:31.571] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-02 17:11:20.599] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-02 19:41:37.489] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-03 01:26:36.718] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-03 05:36:06.864] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-03 08:05:55.309] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-03 14:35:57.13] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-03 16:51:04.890] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-03 18:36:04.921] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-04 05:22:44.195] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-04 07:07:27.586] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-04 08:52:38.680] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-04 10:23:08.227] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-04 12:39:27.649] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-04 14:09:28.579] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-04 15:39:28.73] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-04 16:54:26.105] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-04 19:09:19.593] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-04 20:09:29.388] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-04 21:39:22.948] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-05 00:28:02.918] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-05 02:29:24.299] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-05 05:31:17.967] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-05 07:50:42.908] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-05 09:37:40.513] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-05 11:08:59.958] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-05 12:55:37.971] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-05 14:10:41.199] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-05 15:26:49.389] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-05 16:58:48.768] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-06 01:17:27.810] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-06 02:47:31.935] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-06 04:49:16.259] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-06 06:19:00.432] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-06 08:21:05.6] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-06 10:50:59.62] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-06 14:37:48.984] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-06 18:40:13.19] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-06 19:57:35.727] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-06 21:57:39.482] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-07 04:45:57.982] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-07 07:01:22.893] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-07 09:18:11.399] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-07 11:34:40.475] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-07 15:57:50.663] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-07 16:59:03.685] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-07 18:44:11.357] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-07 20:14:29.314] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-07 21:47:40.446] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-08 04:52:34.530] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-08 08:13:43.194] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-08 09:47:12.955] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-08 13:49:16.152] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-08 15:09:42.825] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-08 16:39:40.52] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-08 17:54:46.391] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-08 19:39:42.187] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-08 23:29:01.279] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 02:30:14.121] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 03:46:22.288] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 04:54:29.906] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 06:08:55.800] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 06:56:11.48] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 08:57:55.256] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 10:13:40.853] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 11:44:03.366] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 12:58:40.476] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 14:14:15.696] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 15:50:58.897] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 17:21:13.165] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 20:55:59.756] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-09 23:28:31.13] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 01:14:04.827] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 02:14:27.840] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 03:29:18.748] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 04:43:56.166] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 05:59:14.333] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 07:28:45.764] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 09:40:25.549] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 10:41:48.92] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 12:12:11.698] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 14:45:03.137] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 16:15:20.667] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 17:15:06.537] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 18:30:00.463] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 19:45:23.744] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 20:46:47.287] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 22:16:50.272] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-10 23:31:54.577] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-11 00:03:39.374] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-11 01:19:03.342] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-11 02:35:34.501] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-11 03:05:11.398] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-11 04:35:09.696] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-11 05:50:35.440] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-11 06:52:01.767] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-11 08:08:58.519] INFO: __init__.create_app @ 31: App startup in production mode
[2022-09-11 09:23:40.514] INFO: __init__.create_app @ 31: App startup in production mode
